#!/bin/bash

# Update Git submodules
git submodule update --init

# Install Python packag
pip install flask flask_cors bs4 lxml pelican markdown geventes using pip


# Optionally, you can add more commands or customizations here.
